### ISSUE TITLE
Update to 1.21 Please

### ISSUE THREAD

**Issue by sternschnaube** [rotgruengelb/seafloor_gardening#1]

**Comment by rotgruengelb** [comment]
Working on it. Thanks for the request!

**Comment by venaminecraft** [comment]
Great 😄

**Comment by rotgruengelb** [comment]
@sternschnaube Done ✅. Uploading Modrinth Version right now.

**Comment by rotgruengelb** [comment]
https://modrinth.com/mod/seafloor_gardening/version/1.0.0+1.21

**Comment by venaminecraft** [comment]
Thanks!

**Comment by rotgruengelb** [comment]
@sternschnaube no problem 💚
